# Generated by Django 5.0 on 2024-06-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="servings_unit",
            field=models.CharField(max_length=65),
        ),
    ]
